# Scikit-learn (sklearn) în română
## Fișă completă, detaliată, cu exemple clare

Notebook-ul acesta este gândit ca material de studiu și recapitulare.

Conține:
- ce este `sklearn`
- cum se gândește biblioteca
- ce module importante are
- când se folosesc
- exemple scurte și clare de cod
- un workflow complet de Machine Learning

## 1. Ce este sklearn

`scikit-learn`, importat în cod ca `sklearn`, este una dintre cele mai folosite biblioteci Python pentru **Machine Learning clasic**.

Pe scurt:
- `numpy` lucrează cu vectori și matrici
- `pandas` lucrează cu tabele
- `sklearn` învață modele din date

### Ce fel de probleme rezolvă
- predicție de prețuri
- clasificare spam / non-spam
- detectare fraudă
- segmentare clienți
- reducere dimensională
- evaluare modele
- pipeline-uri ML

### Ce nu este
`sklearn` nu este biblioteca principală pentru:
- LLM-uri
- deep learning mare
- antrenare pe GPU la scară mare

Pentru acelea se folosesc mai des:
- PyTorch
- TensorFlow
- JAX
- MLX
- Hugging Face

## 2. Ideea centrală din sklearn

Aproape totul în `sklearn` urmează aceleași metode:

- `fit(...)` → modelul învață
- `predict(...)` → modelul prezice
- `transform(...)` → datele sunt transformate
- `fit_transform(...)` → învață transformarea și o aplică

### Schema de bază

```python
model.fit(X_train, y_train)
pred = model.predict(X_test)
```

### Ce sunt `X` și `y`
- `X` = intrările, adică **features**
- `y` = răspunsul corect, adică **target**

Exemplu:
- `X` = kilometri, an, motor
- `y` = prețul mașinii

In [1]:
# Exemplu minimalist de structură sklearn

from sklearn.linear_model import LinearRegression

# X = intrari, y = iesiri
X = [[50], [60], [70], [80]]
y = [100, 120, 140, 160]

model = LinearRegression()
model.fit(X, y)

pred = model.predict([[90]])
print("Predicție pentru 90:", pred[0])

Predicție pentru 90: 180.0


## 3. Subcategoriile mari din sklearn

Cele mai importante zone sunt:

1. `datasets`
2. `model_selection`
3. `preprocessing`
4. `impute`
5. `feature_extraction`
6. `linear_model`
7. `tree`
8. `ensemble`
9. `neighbors`
10. `svm`
11. `naive_bayes`
12. `cluster`
13. `decomposition`
14. `metrics`
15. `pipeline`
16. `inspection`
17. `model persistence`

Le luăm pe rând.

# 4. `sklearn.datasets`

Acest modul îți oferă seturi de date gata de folosit pentru învățare și teste.

## Exemple populare
- `load_iris()` → clasificare flori
- `load_diabetes()` → regresie
- `load_digits()` → imagini cu cifre
- `fetch_california_housing()` → regresie pe prețuri
- `fetch_20newsgroups()` → text

## Când îl folosești
- când înveți ML
- când testezi algoritmi
- când faci demo-uri rapide

In [2]:
from sklearn.datasets import load_iris

data = load_iris(as_frame=True)

print("Numele feature-urilor:", data.feature_names)
print("Target names:", data.target_names)
print(data.frame.head())

Numele feature-urilor: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Target names: ['setosa' 'versicolor' 'virginica']
   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0  


# 5. `sklearn.model_selection`

Acest modul se ocupă de:
- împărțirea datelor
- cross-validation
- tuning de hiperparametri

## Ce conține frecvent
- `train_test_split`
- `cross_val_score`
- `GridSearchCV`
- `RandomizedSearchCV`

## 5.1 `train_test_split`

Împarte datele în:
- train
- test

Uneori mai faci și validation separat.

In [3]:
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_diabetes

data = load_diabetes(as_frame=True)
X = data.data
y = data.target

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print("Train:", X_train.shape, y_train.shape)
print("Test :", X_test.shape, y_test.shape)

Train: (353, 10) (353,)
Test : (89, 10) (89,)


## 5.2 `cross_val_score`

Cross-validation înseamnă că:
- împarți datele în mai multe bucăți
- antrenezi modelul de mai multe ori
- vezi cât de stabil este

### De ce este util
Dacă testezi doar pe un singur split, poți avea:
- un split prea norocos
- un split prea prost

Cross-validation îți dă o estimare mai robustă.

In [4]:
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import Ridge

model = Ridge(alpha=1.0)

scores = cross_val_score(model, X, y, cv=5, scoring="r2")

print("Scoruri R2:", scores)
print("Media R2   :", scores.mean())

Scoruri R2: [0.32166461 0.44048456 0.42210354 0.42466129 0.44196086]
Media R2   : 0.410174971340889


## 5.3 `GridSearchCV`

Caută automat cea mai bună combinație de hiperparametri.

### Ce este un hiperparametru
Este o setare aleasă de tine, nu învățată automat de model.
Exemple:
- `alpha` la Ridge
- `n_estimators` la RandomForest
- `max_depth` la DecisionTree

In [5]:
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import Ridge

param_grid = {
    "alpha": [0.01, 0.1, 1.0, 10.0]
}

grid = GridSearchCV(
    estimator=Ridge(),
    param_grid=param_grid,
    cv=5,
    scoring="r2"
)

grid.fit(X_train, y_train)

print("Cei mai buni parametri:", grid.best_params_)
print("Cel mai bun scor CV   :", grid.best_score_)

Cei mai buni parametri: {'alpha': 0.1}
Cel mai bun scor CV   : 0.45647798015266455


# 6. `sklearn.preprocessing`

Acest modul transformă datele înainte de model.

## Cele mai folosite clase
- `StandardScaler`
- `MinMaxScaler`
- `RobustScaler`
- `OneHotEncoder`
- `PolynomialFeatures`

## 6.1 `StandardScaler`

Transformă fiecare coloană astfel încât:
- media să fie aproape 0
- deviația standard să fie aproape 1

### De ce este util
Unele modele sunt sensibile la scară:
- regresie liniară / ridge / lasso
- logistic regression
- SVM
- KNN
- rețele neurale simple

In [6]:
from sklearn.preprocessing import StandardScaler
import pandas as pd

df = pd.DataFrame({
    "venit": [1000, 2000, 3000, 4000],
    "camere": [2, 3, 4, 5]
})

scaler = StandardScaler()
scaled = scaler.fit_transform(df)

print("Date originale:")
print(df)
print("\nDate scalate:")
print(scaled)

Date originale:
   venit  camere
0   1000       2
1   2000       3
2   3000       4
3   4000       5

Date scalate:
[[-1.34164079 -1.34164079]
 [-0.4472136  -0.4472136 ]
 [ 0.4472136   0.4472136 ]
 [ 1.34164079  1.34164079]]


## 6.2 `MinMaxScaler`

Aduce valorile într-un interval, de obicei `[0, 1]`.

### Când îl folosești
- când vrei valori normalizate într-un interval fix
- la unele rețele neurale sau prelucrări speciale

In [7]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
scaled = scaler.fit_transform(df)

print(scaled)

[[0.         0.        ]
 [0.33333333 0.33333333]
 [0.66666667 0.66666667]
 [1.         1.        ]]


## 6.3 `OneHotEncoder`

Transformă coloanele categorice în coloane numerice.

Exemplu:
- `culoare = rosu, verde, albastru`

devine:
- `culoare_rosu`
- `culoare_verde`
- `culoare_albastru`

### De ce
Modelele sklearn nu înțeleg direct textul brut în majoritatea cazurilor.

In [8]:
from sklearn.preprocessing import OneHotEncoder
import pandas as pd

df_cat = pd.DataFrame({
    "culoare": ["rosu", "verde", "albastru", "rosu"]
})

enc = OneHotEncoder(sparse_output=False)
encoded = enc.fit_transform(df_cat)

print("Coloane noi:", enc.get_feature_names_out())
print(encoded)

Coloane noi: ['culoare_albastru' 'culoare_rosu' 'culoare_verde']
[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]


# 7. `sklearn.impute`

Acest modul se ocupă de valori lipsă.

## Clase importante
- `SimpleImputer`
- `KNNImputer`
- `IterativeImputer`

## 7.1 `SimpleImputer`

Înlocuiește valorile lipsă cu:
- media
- mediana
- cel mai frecvent element
- o constantă

In [9]:
from sklearn.impute import SimpleImputer
import numpy as np

X_missing = np.array([
    [1, 10],
    [2, np.nan],
    [3, 30],
    [4, np.nan]
])

imp = SimpleImputer(strategy="median")
X_filled = imp.fit_transform(X_missing)

print(X_filled)

[[ 1. 10.]
 [ 2. 20.]
 [ 3. 30.]
 [ 4. 20.]]


# 8. `sklearn.feature_extraction`

Transformă date brute în feature-uri numerice.

## Foarte util pentru text
Clase importante:
- `CountVectorizer`
- `TfidfVectorizer`
- `DictVectorizer`
- `FeatureHasher`

## 8.1 `CountVectorizer`

Numără de câte ori apare fiecare cuvânt.

In [10]:
from sklearn.feature_extraction.text import CountVectorizer

docs = [
    "pisica mananca peste",
    "cainele mananca carne",
    "pisica doarme"
]

vec = CountVectorizer()
X_counts = vec.fit_transform(docs)

print("Vocabular:", vec.get_feature_names_out())
print(X_counts.toarray())

Vocabular: ['cainele' 'carne' 'doarme' 'mananca' 'peste' 'pisica']
[[0 0 0 1 1 1]
 [1 1 0 1 0 0]
 [0 0 1 0 0 1]]


## 8.2 `TfidfVectorizer`

Este o versiune mai inteligentă decât simpla numărare.
Pune accent pe cuvintele importante și reduce greutatea celor foarte comune.

### Când îl folosești
- clasificare text
- filtrare spam
- analiză documente
- NLP clasic

In [11]:
from sklearn.feature_extraction.text import TfidfVectorizer

vec = TfidfVectorizer()
X_tfidf = vec.fit_transform(docs)

print("Vocabular:", vec.get_feature_names_out())
print(X_tfidf.toarray())

Vocabular: ['cainele' 'carne' 'doarme' 'mananca' 'peste' 'pisica']
[[0.         0.         0.         0.51785612 0.68091856 0.51785612]
 [0.62276601 0.62276601 0.         0.4736296  0.         0.        ]
 [0.         0.         0.79596054 0.         0.         0.60534851]]


# 9. `sklearn.linear_model`

Modele liniare pentru regresie și clasificare.

## Clase foarte importante
- `LinearRegression`
- `Ridge`
- `Lasso`
- `ElasticNet`
- `LogisticRegression`

## 9.1 `LinearRegression`

Învață o relație de forma:

`y = w1*x1 + w2*x2 + ... + b`

### Când îl folosești
- regresie simplă
- baseline model
- interpretabilitate

In [12]:
from sklearn.linear_model import LinearRegression
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error

data = load_diabetes(as_frame=True)
X = data.data
y = data.target

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

lr = LinearRegression()
lr.fit(X_train, y_train)
pred = lr.predict(X_test)

print("MAE:", mean_absolute_error(y_test, pred))
print("Coeficienți:", lr.coef_[:5])
print("Intercept:", lr.intercept_)

MAE: 42.79409467959994
Coeficienți: [  37.90402135 -241.96436231  542.42875852  347.70384391 -931.48884588]
Intercept: 151.34560453985995


## 9.2 `Ridge`

Este tot regresie liniară, dar cu regularizare L2.

### Ce înseamnă asta
Modelul este penalizat dacă face coeficienți prea mari.

### De ce e util
- reduce overfitting
- stabilizează modelul
- merge bine pe multe probleme tabulare

In [13]:
from sklearn.linear_model import Ridge

ridge = Ridge(alpha=1.0)
ridge.fit(X_train, y_train)
pred = ridge.predict(X_test)

print("MAE:", mean_absolute_error(y_test, pred))
print("Coeficienți:", ridge.coef_[:5])

MAE: 46.13885766697452
Coeficienți: [ 45.36737726 -76.66608563 291.33883165 198.99581745  -0.53030959]


## 9.3 `Lasso`

Regularizare L1.

### Efect important
Poate împinge unii coeficienți exact la 0.

### De ce e util
- selecție automată de feature-uri
- modele mai sparse, mai simple

In [ ]:
from sklearn.linear_model import Lasso

lasso = Lasso(alpha=0.1)
lasso.fit(X_train, y_train)

print("Coeficienți:", lasso.coef_[:10])

## 9.4 `LogisticRegression`

Deși are în nume „regression”, se folosește pentru **clasificare**.

### Când îl folosești
- probleme binare
- clasificare multi-clasă simplă
- baseline foarte bun

In [14]:
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

iris = load_iris(as_frame=True)
X = iris.data
y = iris.target

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

clf = LogisticRegression(max_iter=1000)
clf.fit(X_train, y_train)
pred = clf.predict(X_test)

print("Accuracy:", accuracy_score(y_test, pred))

Accuracy: 1.0


# 10. `sklearn.tree`

Modele bazate pe reguli de tipul:
- dacă...
- altfel...

## Clase importante
- `DecisionTreeClassifier`
- `DecisionTreeRegressor`

### Avantaje
- ușor de înțeles
- merg și pe relații neliniare
- nu cer neapărat scalare

### Dezavantaje
- pot face overfitting

In [15]:
from sklearn.tree import DecisionTreeClassifier

tree = DecisionTreeClassifier(max_depth=3, random_state=42)
tree.fit(X_train, y_train)
pred = tree.predict(X_test)

print("Accuracy:", accuracy_score(y_test, pred))

Accuracy: 1.0


# 11. `sklearn.ensemble`

Combinații de mai multe modele.

## Clase importante
- `RandomForestClassifier`
- `RandomForestRegressor`
- `GradientBoostingClassifier`
- `GradientBoostingRegressor`
- `AdaBoost`
- `ExtraTrees`

## 11.1 `RandomForest`

Construiește mulți arbori și combină rezultatele lor.

### De ce e popular
- puternic pe date tabulare
- robust
- puțină preprocesare
- merge bine „din cutie”

In [16]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score

data = load_diabetes(as_frame=True)
X = data.data
y = data.target

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

rf = RandomForestRegressor(n_estimators=100, random_state=42)
rf.fit(X_train, y_train)
pred = rf.predict(X_test)

print("R2:", r2_score(y_test, pred))

R2: 0.4428225673999313


# 12. `sklearn.neighbors`

Modele bazate pe vecinii cei mai apropiați.

## Clase importante
- `KNeighborsClassifier`
- `KNeighborsRegressor`
- `NearestNeighbors`

### Idee
Un punct nou este evaluat după punctele cele mai apropiate din datele de antrenare.

### Când îl folosești
- pentru experimente simple
- pentru intuiție
- seturi de date mici și medii

In [17]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)
pred = knn.predict(X_test)

print("Accuracy:", accuracy_score(y_test, pred))

Accuracy: 0.0


/Users/cosmin/Doc/.venv1/lib/python3.14/site-packages/sklearn/neighbors/_base.py:501: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)


# 13. `sklearn.svm`

Support Vector Machines.

## Clase importante
- `SVC`
- `SVR`
- `LinearSVC`
- `LinearSVR`

### Când le folosești
- multe dimensiuni
- date nu foarte mari
- separare bună între clase

### Observație
De obicei au nevoie de scalare.

In [18]:
from sklearn.svm import SVC
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

svm_model = Pipeline([
    ("scaler", StandardScaler()),
    ("model", SVC())
])

svm_model.fit(X_train, y_train)
pred = svm_model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, pred))

Accuracy: 0.0


/Users/cosmin/Doc/.venv1/lib/python3.14/site-packages/sklearn/svm/_base.py:755: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)


# 14. `sklearn.naive_bayes`

Modele rapide bazate pe teorema lui Bayes.

## Clase importante
- `GaussianNB`
- `MultinomialNB`
- `BernoulliNB`

### Când îl folosești
- clasificare text
- baseline rapid
- probleme simple

In [19]:
from sklearn.naive_bayes import GaussianNB

nb_model = GaussianNB()
nb_model.fit(X_train, y_train)
pred = nb_model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, pred))

Accuracy: 0.0


# 15. `sklearn.cluster`

Pentru grupare fără etichete.

## Clase importante
- `KMeans`
- `DBSCAN`
- `AgglomerativeClustering`

## 15.1 `KMeans`

Împarte datele în `k` grupuri.

### Când îl folosești
- segmentare clienți
- grupare puncte similare
- explorare nesupervizată

In [20]:
from sklearn.cluster import KMeans
from sklearn.datasets import load_iris

iris = load_iris(as_frame=True)
X = iris.data

kmeans = KMeans(n_clusters=3, random_state=42)
labels = kmeans.fit_predict(X)

print("Primele 10 etichete de cluster:", labels[:10])

Primele 10 etichete de cluster: [1 1 1 1 1 1 1 1 1 1]


# 16. `sklearn.decomposition`

Reduce dimensiunea datelor.

## Clase importante
- `PCA`
- `TruncatedSVD`
- `NMF`

## 16.1 `PCA`

Principal Component Analysis.

### Ce face
Transformă datele în mai puține dimensiuni, păstrând cât mai multă informație.

### Când îl folosești
- vizualizare
- reducere zgomot
- compresie
- accelerare

In [21]:
from sklearn.decomposition import PCA
from sklearn.datasets import load_iris

iris = load_iris(as_frame=True)
X = iris.data

pca = PCA(n_components=2)
X_reduced = pca.fit_transform(X)

print("Forma inițială :", X.shape)
print("Forma redusă   :", X_reduced.shape)

Forma inițială : (150, 4)
Forma redusă   : (150, 2)


# 17. `sklearn.metrics`

Acest modul măsoară cât de bun este modelul.

## Pentru regresie
- `mean_absolute_error`
- `mean_squared_error`
- `r2_score`

## Pentru clasificare
- `accuracy_score`
- `precision_score`
- `recall_score`
- `f1_score`
- `confusion_matrix`

## 17.1 Regresie

In [22]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

y_true = np.array([10, 20, 30, 40])
y_pred = np.array([12, 18, 33, 39])

print("MAE :", mean_absolute_error(y_true, y_pred))
print("MSE :", mean_squared_error(y_true, y_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_true, y_pred)))
print("R2  :", r2_score(y_true, y_pred))

MAE : 2.0
MSE : 4.5
RMSE: 2.1213203435596424
R2  : 0.964


## 17.2 Clasificare

In [23]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

y_true = [1, 0, 1, 1, 0, 1]
y_pred = [1, 0, 1, 0, 0, 1]

print("Accuracy :", accuracy_score(y_true, y_pred))
print("Precision:", precision_score(y_true, y_pred))
print("Recall   :", recall_score(y_true, y_pred))
print("F1       :", f1_score(y_true, y_pred))
print("Confusion matrix:\n", confusion_matrix(y_true, y_pred))

Accuracy : 0.8333333333333334
Precision: 1.0
Recall   : 0.75
F1       : 0.8571428571428571
Confusion matrix:
 [[2 0]
 [1 3]]


# 18. `sklearn.pipeline`

Pipeline este una dintre cele mai importante idei din sklearn.

### Ce face
Leagă mai mulți pași într-un singur obiect.

Exemplu:
- imputare
- scalare
- model

### De ce e util
- cod mai curat
- mai puține greșeli
- aceeași transformare pe train și test
- foarte bun pentru proiecte reale

In [24]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Ridge
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error

data = load_diabetes(as_frame=True)
X = data.data
y = data.target

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

pipe = Pipeline([
    ("scaler", StandardScaler()),
    ("model", Ridge(alpha=1.0))
])

pipe.fit(X_train, y_train)
pred = pipe.predict(X_test)

print("MAE:", mean_absolute_error(y_test, pred))

MAE: 42.81199941834889


# 19. `sklearn.inspection`

Aici intră metode pentru a înțelege modelul.

## Foarte important
- `permutation_importance`

### Cum funcționează
1. calculezi scorul modelului normal
2. strici o coloană, amestecând valorile
3. vezi cât scade performanța

Dacă scade mult, feature-ul este important.

In [25]:
from sklearn.inspection import permutation_importance
from sklearn.ensemble import RandomForestRegressor
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split

data = load_diabetes(as_frame=True)
X = data.data
y = data.target

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = RandomForestRegressor(random_state=42)
model.fit(X_train, y_train)

result = permutation_importance(model, X_test, y_test, n_repeats=10, random_state=42)

for feature, importance in sorted(
    zip(X.columns, result.importances_mean),
    key=lambda x: x[1],
    reverse=True
)[:5]:
    print(feature, round(float(importance), 4))

s5 0.2512
bmi 0.2241
bp 0.0244
s6 0.0212
sex 0.0209


# 20. Salvarea modelului

După ce ai antrenat un model, îl poți salva pe disc.

### De ce
- nu îl mai antrenezi de la zero
- îl folosești mai târziu
- îl pui în aplicații

In [26]:
from joblib import dump, load
from sklearn.linear_model import Ridge

model = Ridge(alpha=1.0)
model.fit(X_train, y_train)

dump(model, "model_ridge.joblib")

model_loaded = load("model_ridge.joblib")
pred = model_loaded.predict(X_test[:3])

print(pred)

[157.28546958 163.0077872  155.18015341]


# 21. Workflow complet sklearn, de la zero

Așa arată un proiect ML simplu și corect:

1. alegi problema
2. încarci datele
3. separi `X` și `y`
4. faci `train_test_split`
5. alegi un baseline model
6. creezi un pipeline
7. faci cross-validation
8. faci tuning
9. evaluezi final
10. salvezi modelul

In [27]:
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_absolute_error, r2_score
import numpy as np

# 1. date
data = load_diabetes(as_frame=True)
X = data.data
y = data.target

# 2. split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# 3. pipeline
pipe = Pipeline([
    ("scaler", StandardScaler()),
    ("model", Ridge())
])

# 4. cross-validation
scores = cross_val_score(pipe, X_train, y_train, cv=5, scoring="r2")
print("CV R2 mean:", scores.mean())

# 5. tuning
grid = GridSearchCV(
    pipe,
    param_grid={"model__alpha": [0.01, 0.1, 1.0, 10.0]},
    cv=5,
    scoring="r2"
)
grid.fit(X_train, y_train)

best_model = grid.best_estimator_
print("Best params:", grid.best_params_)

# 6. test final
pred = best_model.predict(X_test)
print("MAE:", mean_absolute_error(y_test, pred))
print("R2 :", r2_score(y_test, pred))

CV R2 mean: 0.4512662709279831
Best params: {'model__alpha': 10.0}
MAE: 42.856825247800614
R2 : 0.45721095677808476


# 22. Cum alegi ce folosești

## Dacă problema este regresie
Începi cu:
- `LinearRegression`
- `Ridge`
- `RandomForestRegressor`

## Dacă problema este clasificare
Începi cu:
- `LogisticRegression`
- `RandomForestClassifier`
- `SVC`
- `KNeighborsClassifier`

## Dacă problema este clustering
Începi cu:
- `KMeans`
- `DBSCAN`

## Dacă ai text
Începi cu:
- `CountVectorizer`
- `TfidfVectorizer`
- apoi un clasificator

## Dacă ai valori lipsă
Adaugi:
- `SimpleImputer`

## Dacă ai categorice
Adaugi:
- `OneHotEncoder`

## Dacă ai modele sensibile la scară
Adaugi:
- `StandardScaler`

# 23. Greșeli comune în sklearn

## 1. Faci `fit` pe tot datasetul
Greșit, pentru că modelul vede și testul.

## 2. Scalezi separat train și test greșit
Corect este:
- `fit` pe train
- `transform` pe test

Pipeline-ul rezolvă asta corect.

## 3. Folosești test set-ul pentru tuning
Greșit. Test set-ul este doar pentru evaluarea finală.

## 4. Alegi metrici nepotrivite
Exemplu:
- la fraudă, `accuracy` poate înșela
- la regresie, `RMSE` și `MAE` spun lucruri diferite

## 5. Vrei direct model complex
Mai bine începi cu baseline simplu și compari.

# 24. Ordinea bună pentru învățare

Dacă vrei să înveți sklearn logic, ordinea bună este:

1. `load_iris`, `load_diabetes`
2. `train_test_split`
3. `LinearRegression`
4. `LogisticRegression`
5. `StandardScaler`
6. `Pipeline`
7. `cross_val_score`
8. `GridSearchCV`
9. `DecisionTree`
10. `RandomForest`
11. `KMeans`
12. `PCA`
13. `permutation_importance`

Așa înțelegi întâi scheletul, apoi modelele.

# 25. Rezumat final

## Ce este sklearn
Bibliotecă Python pentru machine learning clasic.

## La ce se folosește
- regresie
- clasificare
- clustering
- reducere dimensională
- evaluare
- pipeline-uri

## Module de bază
- `datasets`
- `model_selection`
- `preprocessing`
- `linear_model`
- `tree`
- `ensemble`
- `neighbors`
- `svm`
- `cluster`
- `decomposition`
- `metrics`
- `pipeline`
- `inspection`

## Formula mentală simplă
`date → transformare → model → evaluare`

## Ce merită reținut
- aproape toate modelele au `fit()` și `predict()`
- aproape toate transformările au `fit()`, `transform()`, `fit_transform()`
- `Pipeline` este foarte important
- `cross-validation` și `GridSearchCV` sunt esențiale
- `sklearn` este excelent pentru ML clasic, nu pentru LLM-uri